### ISSUE TITLE
运行mmseg的时候报错

### ISSUE THREAD

**Issue by wanming** [mawenbao/coreseek-scripts#2]
在根据 http://blog.atime.me/note/mmseg-custom-dict.html 的步骤一步步操作的时候，执行 ` /usr/local/mmseg3/bin/mmseg -u /usr/local/mmseg3/etc/unigram.txt `这一步的时候报错了，提示 `[1]    99444 segmentation fault  /usr/local/mmseg3/bin/mmseg -u /usr/local/mmseg3/etc/unigram.txt`，怎么破？

**Comment by mawenbao** [comment]
没遇到过这种错误，你看下unigram.txt是不是UTF-8编码的`file /usr/local/mmseg3/etc/unigram.txt`，如果还不行，可以看下coreseek的[FAQ](/usr/local/mmseg3/etc/unigram.txt)。

**Comment by wanming** [comment]
解决了，导致这个问题的原因可能是下面其中之一：
1. 词典路径设置不正确
2. 自己构造的词典数据过多
