### ISSUE TITLE
please provide a version to support python 3.3+

### ISSUE THREAD

**Issue by vincent3i** [mawenbao/coreseek-scripts#3]
There is a big change from python 2.7+ to 3.3+, which makes extract-sougou-dict.py can not run as expected.

for example,
Python 3.3

when I execute the command
```python
extract-sougou-dict.py sougou/*.scel -o sougou-dict.txt -mmseg
```
NameError: global name 'xrange' is not defined will be thrown.

change xrange to range may be fixed this version unmatched problem.

and when 
```python
./merge-mmseg-dict.py -a unigram.txt -b sougou-dict.txt -o merged.txt
```
there will be a problem, ImportError: cannot import name imap

to fix it, should comment line 11
#from itertools import imap, ifilter

and change line 15
imap to map
ifilter to filter

for more details to upgrade from 2.7+ to 3.3+
http://woodpecker.org.cn/diveintopython3/porting-code-to-python-3-with-2to3.html

Sincerely

**Comment by mawenbao** [comment]
Hello,
Thanks. Tthe latest commit fixed this issue. The two scripts support python3 now.
